<?php
$order = new Mage_Sales_Model_Order();
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$order->loadByIncrementId($orderId);
?>
<h2><?php echo $this->__('Coinfide Payment Gateway') ?></h2>
<p>Please wait while you are being redirected...</p>
<form name="coinfidepaymentmethod" method="post" action="<?php echo Mage::helper('coinfidepaymentmethod')->getPaymentGatewayUrl(); ?>">
  <input type="hidden" name="orderId" value="<?php echo $orderId; ?>">
  <input type="submit" value="<?php echo $this->__('Make Payment') ?>" />
</form>